services:
  timescaledb:
    image: timescale/timescaledb:2.28.3-pg17
    container_name: repacss_env_db
    environment:
      POSTGRES_PASSWORD: [placeholder]
      POSTGRES_USER: repacss
      POSTGRES_DB: repacss
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  timescale_data:
