; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
; PlatformIO Project Configuration File

[platformio]
default_envs = 

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

upload_flags =
  --before=default_reset
  --after=hard_reset

test_framework = unity
test_build_src = yes

lib_deps =
  paulstoffregen/OneWire@^2.3.8
  milesburton/DallasTemperature@^3.11.0
  arduino-libraries/Ethernet@^2.0.2
  knolleary/PubSubClient@^2.8
  bblanchon/ArduinoJson
; Shared compile-time config for BOTH ESP32s
build_flags =

[env:esp32_a]
build_flags =
  ${env.build_flags}
  ; -DDEVICE_ID=65
targets = upload, monitor
;port for ESP32 A
upload_port  = /dev/cu.usbserial-0001
monitor_port = /dev/cu.usbserial-0001

[env:esp32_b]
build_flags =
  ${env.build_flags}
  ; -DDEVICE_ID=66
targets = upload, monitor
;port for ESP32 B
upload_port  = /dev/cu.usbserial-3
monitor_port = /dev/cu.usbserial-3
